name = "cldcde-api"
main = "src/worker-v2.ts"
compatibility_date = "2024-01-01"

[build]
command = "bun run build"

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_PREVIEW_ID"

[vars]
ENVIRONMENT = "production"

# Secrets to be set via wrangler secret put:
# SUPABASE_URL
# SUPABASE_ANON_KEY
# SUPABASE_SERVICE_KEY
# MEILISEARCH_HOST
# MEILISEARCH_KEY
# SENTRY_DSN (optional)