name = "cldcde-api"
main = "src/worker-ultra.ts"
compatibility_date = "2024-01-01"

# Just one KV namespace for caching - that's it!
[[kv_namespaces]]
binding = "CACHE"
id = "286857936dc34015958930dbd42f0456"

# No D1, no R2, no queues, no durable objects
# Just KV for caching. Everything else is in Supabase!

# Secrets (set via wrangler secret put):
# - SUPABASE_URL
# - SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_KEY
# - OPENROUTER_API_KEY