# CLDCDE Pro Prometheus Configuration
# By CloudOracle - Production Ready

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cldcde-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CLDCDE Pro API Server
  - job_name: 'cldcde-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 10s

  # NGINX metrics (if enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  # PostgreSQL metrics (if exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  # Redis metrics (if exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 512MB