[package]
name = "github-integration"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
anyhow.workspace = true
octocrab.workspace = true