/**
 * Output Emitter — writes the complete template ecosystem to disk
 * as a set of JSON manifest files and a folder architecture.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { TemplateManifest, FolderArchitecture } from "./types.js";

export function emitOutput(
  manifest: TemplateManifest,
  folderArchitecture: FolderArchitecture,
  opts: { outputDir: string; log?: (e: Record<string, unknown>) => void },
): string[] {
  const { outputDir, log = () => {} } = opts;
  const files: string[] = [];

  const write = (relPath: string, data: unknown): void => {
    const fullPath = join(outputDir, relPath);
    mkdirSync(dirname(fullPath), { recursive: true });
    writeFileSync(fullPath, JSON.stringify(data, null, 2), "utf-8");
    files.push(relPath);
  };

  // ── Main manifest ─────────────────────────────────────────────────
  write("manifest.json", manifest);

  // ── Section library ───────────────────────────────────────────────
  write("sections.json", manifest.sectionLibrary);

  // ── Component library ─────────────────────────────────────────────
  write("components.json", manifest.componentLibrary);

  // ── Motion library ────────────────────────────────────────────────
  write("motions.json", {
    presets: manifest.animationLibrary,
    motionDNA: manifest.motionDNA,
  });

  // ── Page inventory ────────────────────────────────────────────────
  write("pages.json", {
    pageDNA: manifest.pageDNA,
    siteGraph: manifest.siteGraph,
  });

  // ── Design tokens ─────────────────────────────────────────────────
  write("tokens.json", manifest.designTokens);

  // ── Placeholder catalog ───────────────────────────────────────────
  write("placeholders.json", manifest.placeholderCatalog);

  // ── Compatibility graph ───────────────────────────────────────────
  write("compatibility.json", manifest.compatibilityGraph);

  // ── Media schemas ─────────────────────────────────────────────────
  write("media.json", manifest.mediaSchemas);

  // ── CMS schemas ───────────────────────────────────────────────────
  write("cms.json", manifest.cmsSchema);

  // ── Experience timeline ───────────────────────────────────────────
  write("timeline.json", manifest.experienceTimeline);

  // ── Accessibility report ──────────────────────────────────────────
  write("accessibility.json", manifest.accessibilityReport);

  // ── Performance report ────────────────────────────────────────────
  write("performance.json", manifest.performanceReport);

  // ── SEO report ────────────────────────────────────────────────────
  write("seo.json", manifest.seoReport);

  // ── Benchmark scores ──────────────────────────────────────────────
  write("benchmark.json", manifest.benchmark);

  // ── Site graph ────────────────────────────────────────────────────
  write("site-graph.json", manifest.siteGraph);

  // ── Builder specification ─────────────────────────────────────────
  write("builder-spec.json", manifest.builderSpec);

  // ── Themes ────────────────────────────────────────────────────────
  write("themes.json", manifest.themes);

  // ── Pattern recognition ───────────────────────────────────────────
  write("patterns.json", manifest.patternRecognition);

  // ── QA report ─────────────────────────────────────────────────────
  write("qa.json", manifest.qaReport);

  // ── Folder architecture ───────────────────────────────────────────
  write("folder-architecture.json", folderArchitecture);

  // ── Executive summary (human-readable) ────────────────────────────
  write("executive-summary.md", buildExecutiveSummary(manifest, folderArchitecture));

  log({ phase: "emit", files: files.length });
  return files;
}

function buildExecutiveSummary(manifest: TemplateManifest, folderArch: FolderArchitecture): string {
  const lines: string[] = [
    "# AEGNTIC Website Intelligence Engine — Executive Analysis",
    "",
    `**Source URL:** ${manifest.sourceUrl}`,
    `**Template ID:** ${manifest.templateId}`,
    `**Version:** ${manifest.version}`,
    `**Generated:** ${manifest.generatedAt}`,
    "",
    "## Overview",
    "",
    `This template ecosystem was generated by analyzing ${manifest.siteGraph.totalPages} page(s) from the reference site.`,
    `The analysis extracted ${manifest.sectionLibrary.length} sections, ${manifest.componentLibrary.length} components,`,
    `and ${manifest.animationLibrary.length} motion presets as reusable, original artifacts.`,
    "",
    "## Site Graph",
    "",
    `- **Entry URL:** ${manifest.siteGraph.entryUrl}`,
    `- **Total Pages:** ${manifest.siteGraph.totalPages}`,
    `- **Origin:** ${manifest.siteGraph.origin}`,
    "",
    "### Page Inventory",
    "",
    "| Path | Type | Purpose | Sections | SEO Weight |",
    "|------|------|---------|----------|------------|",
    ...manifest.pageDNA.map((p) => `| ${p.path} | ${p.pageType} | ${p.purpose} | ${p.sectionCount} | ${p.seoWeight} |`),
    "",
    "## Information Architecture",
    "",
    "The site follows a clear hierarchy with distinct page types supporting different user intents.",
    "",
    "## Motion DNA",
    "",
    `- **Motion Presets:** ${manifest.animationLibrary.length}`,
    `- **Scroll Smoothing:** ${manifest.motionDNA.scrollSmoothing.enabled ? "Enabled" : "Disabled"}`,
    `- **Easing Philosophy:** ${manifest.motionDNA.easingPhilosophy.primary}`,
    `- **Reveal Strategy:** ${manifest.motionDNA.revealSequencing.strategy}`,
    `- **Stagger Cadence:** ${manifest.motionDNA.staggerCadence}ms`,
    `- **Emotional Tone:** ${manifest.motionDNA.emotionalRhythm.tone}`,
    "",
    "## Design Tokens",
    "",
    `- **Colors:** ${Object.keys(manifest.designTokens.colors).length}`,
    `- **Spacing Scale:** ${Object.keys(manifest.designTokens.spacing).length} steps`,
    `- **Typography:** ${Object.keys(manifest.designTokens.typography.fontFamily).length} font families`,
    `- **Shadows:** ${Object.keys(manifest.designTokens.shadows).length}`,
    `- **Radius:** ${Object.keys(manifest.designTokens.radius).length}`,
    "",
    "## Component Library",
    "",
    "| Component | Category | Instances | Props | Variants |",
    "|-----------|----------|-----------|-------|----------|",
    ...manifest.componentLibrary.map((c) => `| ${c.name} | ${c.category} | ${c.instances} | ${c.props.length} | ${c.variants.length} |`),
    "",
    "## Section Library",
    "",
    "| Section | Category | Archetype | Responsive Rules | Compatibility |",
    "|---------|----------|-----------|------------------|---------------|",
    ...manifest.sectionLibrary.map((s) => `| ${s.name} | ${s.category} | ${s.archetype} | ${s.responsiveRules.length} | ${s.compatibilityScore} |`),
    "",
    "## Placeholder Catalog",
    "",
    `Total placeholders: ${manifest.placeholderCatalog.placeholders.length}`,
    "",
    "Every editable value has been replaced with a semantic placeholder carrying purpose, tone,",
    "length guidance, accessibility guidance, SEO guidance, and an example.",
    "",
    "## CMS Schemas",
    "",
    "| Platform | Collections | Globals |",
    "|----------|-------------|---------|",
    ...manifest.cmsSchema.map((c) => `| ${c.cms} | ${c.collections.length} | ${c.globals.length} |`),
    "",
    "## Benchmark Scores",
    "",
    "| Metric | Score |",
    "|--------|-------|",
    `| Performance | ${manifest.benchmark.performance} |`,
    `| Accessibility | ${manifest.benchmark.accessibility} |`,
    `| SEO | ${manifest.benchmark.seo} |`,
    `| Animation Density | ${manifest.benchmark.animationDensity} |`,
    `| Complexity | ${manifest.benchmark.complexity} |`,
    `| Bundle Estimate | ${Math.round(manifest.benchmark.bundleEstimate / 1024)}KB |`,
    `| **Overall** | **${manifest.benchmark.overall}** |`,
    "",
    "## Builder Specification",
    "",
    `- **Features:** ${manifest.builderSpec.features.length}`,
    `- **Panels:** ${manifest.builderSpec.panels.length}`,
    `- **AI Features:** ${manifest.builderSpec.aiFeatures.length}`,
    "",
    "### AI Capabilities",
    "",
    ...manifest.builderSpec.aiFeatures.map((f) => `- **${f.name}:** ${f.description}`),
    "",
    "## Accessibility Report",
    "",
    `- **Overall Score:** ${manifest.accessibilityReport.overallScore}/100`,
    `- **WCAG Level:** ${manifest.accessibilityReport.wcagLevel}`,
    `- **Issues:** ${manifest.accessibilityReport.issues.length}`,
    `- **Passes:** ${manifest.accessibilityReport.passes.length}`,
    "",
    "## Performance Report",
    "",
    `- **Overall Score:** ${manifest.performanceReport.overallScore}/100`,
    `- **FCP Estimate:** ${manifest.performanceReport.metrics.fcpEstimate}ms`,
    `- **LCP Estimate:** ${manifest.performanceReport.metrics.lcpEstimate}ms`,
    `- **CLS Estimate:** ${manifest.performanceReport.metrics.clsEstimate}`,
    `- **Bundle Estimate:** ${Math.round(manifest.performanceReport.bundleEstimate / 1024)}KB`,
    "",
    "## SEO Report",
    "",
    `- **Overall Score:** ${manifest.seoReport.overallScore}/100`,
    `- **Issues:** ${manifest.seoReport.issues.length}`,
    `- **Passes:** ${manifest.seoReport.passes.length}`,
    "",
    "## Experience Timeline",
    "",
    `The timeline captures ${manifest.experienceTimeline.events.length} events across the user journey.`,
    "",
    "## QA Report",
    "",
    `- **Passed:** ${manifest.qaReport.passed ? "Yes" : "No"}`,
    `- **Checks:** ${manifest.qaReport.checks.length}`,
    `- **Passed Checks:** ${manifest.qaReport.checks.filter((c) => c.passed).length}`,
    `- **Iterations:** ${manifest.qaReport.iterations}`,
    "",
    "## Folder Architecture",
    "",
    "```",
    folderArch.root + "/",
    ...flattenFolder(folderArch.structure, "  "),
    "```",
    "",
    "## Implementation Roadmap",
    "",
    "1. **Install template ecosystem** — Copy the generated files into your project",
    "2. **Configure CMS** — Choose a CMS platform and import the schema",
    "3. **Customize tokens** — Adjust design tokens to match your brand",
    "4. **Populate placeholders** — Replace semantic placeholders with real content",
    "5. **Upload media** — Replace upload zones with your images and videos",
    "6. **Apply theme** — Select and customize a theme",
    "7. **Test** — Run accessibility, performance, and SEO audits",
    "8. **Deploy** — Build and deploy the template",
    "",
    "---",
    "",
    "*Generated by the AEGNTIC Website Intelligence Engine. The generated implementation is original, reusable, configurable, accessible, and compatible with a growing library of interchangeable sections and motion presets.*",
  ];

  return lines.join("\n");
}

function flattenFolder(nodes: FolderArchitecture["structure"], indent: string): string[] {
  const out: string[] = [];
  for (const node of nodes) {
    const icon = node.type === "directory" ? "+" : "-";
    out.push(`${indent}${icon} ${node.name}`);
    if (node.children) {
      out.push(...flattenFolder(node.children, indent + "  "));
    }
  }
  return out;
}
